name: Update GitHub Stats

on:
  schedule:
    - cron: '0 * * * *'  # Runs at the start of every hour
  workflow_dispatch: # Allows for manual triggering

jobs:
  update-stats:
    runs-on: ubuntu-latest

    steps:
      - name: Check out the repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16' # Use the latest Node.js LTS version

      - name: Install dependencies
        run: npm install

      - name: Run the stats generation script
        env:
          GITHUB_TOKEN: ${{ secrets.SECURING_TOKEN }}
        run: node generateCard.js

      - name: Ensure `stats_board.svg` is tracked
        run: |
          git add stats_board.svg
          git status # Debug: Check that stats_board.svg is in the staging area

      - name: Commit and push changes if needed
        env:
          GITHUB_TOKEN: ${{ secrets.SECURING_TOKEN }}
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          if git diff --cached --quiet; then
            echo "No changes detected in stats_board.svg. Skipping commit.";
          else
            git commit -m "Update stats board SVG with new data"
            git push
          fi
