name: Update GitHub Stats

on:
  schedule:
    - cron: '0 0 * * *'  # Runs daily at midnight (UTC)
  workflow_dispatch: # Allows for manual triggering

jobs:
  update-stats:
    runs-on: ubuntu-latest

    steps:
      - name: Check out the repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install requests

      - name: Run the contribution fetch script
        env:
          GITHUB_TOKEN: ${{ secrets.SECURING_TOKEN }}
        run: |
          python fetch_contributions.py
