# .github/workflows/update-stats.yml
name: Update GitHub Stats

on:
  schedule:
    - cron: '*/5 * * * *'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  update-stats:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install Dependencies
        run: npm install

      - name: Run the stats generation script
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_USERNAME: YourGitHubUsername
        run: |
          echo "Running generateCard.js..."
          node generateCard.js
          echo "generateCard.js completed."

      - name: Configure Git Identity
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git config --global push.default simple
          git config --list

      - name: Switch to main branch
        run: |
          git fetch origin main
          git checkout main
          git pull origin main

      - name: Stage and Add SVG
        run: |
          git add stats_board.svg
          git status

      - name: Commit and Push the Updated SVG
        run: |
          if git diff --cached --quiet; then
            echo "No changes detected in stats_board.svg. Skipping commit.";
          else
            git commit -m "Update stats board SVG with new data"
            git push origin main
          fi
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
