name: Update GitHub Stats

on:
  schedule:
    - cron: '*/60 * * * *'  # Runs every hour
  workflow_dispatch: # Allows for manual triggering

jobs:
  update-stats:
    runs-on: ubuntu-latest

    steps:
      - name: Check out the repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install dependencies
        run: npm install

      - name: Run the stats generation script
        env:
          GITHUB_TOKEN: ${{ secrets.SECURING_TOKEN }}
        run: node generateCard.js

      - name: Check Git status before commit
        run: git status

      - name: Commit and push the updated SVG
        env:
          GITHUB_TOKEN: ${{ secrets.SECURING_TOKEN }}
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add -f stats_board.svg
          git commit -m "Update stats board SVG with new data" || echo "No changes to commit"
          git push
