name: Update GitHub Stats

on:
  schedule:
    - cron: '*/5 * * * *'  # Runs every 5 minutes
  workflow_dispatch: # Allows for manual triggering

jobs:
  update-stats:
    runs-on: ubuntu-latest

    steps:
      - name: Check out the repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0 # Fetch all branches

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Install dependencies
        run: npm install

      - name: Run the stats generation script
        env:
          GITHUB_TOKEN: ${{ secrets.SECURING_TOKEN }}
        run: node generateCard.js

      - name: Configure Git Identity
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"

      - name: Switch to main branch
        run: |
          git fetch origin main
          git checkout main
          git pull origin main

      - name: Merge js into main
        run: |
          git merge js || echo "Already up to date."

      - name: Stage and Add SVG
        run: |
          git add stats_board.svg
          git status

      - name: Commit and Push the Updated SVG
        env:
          GITHUB_TOKEN: ${{ secrets.SECURING_TOKEN }}
        run: |
          if git diff --cached --quiet; then
            echo "No changes detected in stats_board.svg. Skipping commit.";
          else
            git commit -m "Update stats board SVG with new data"
            git push origin main
          fi
